version: "3.8"

services:
  app:
    build: .
    container_name: products_crud_api_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/products_logs
      - SQLALCHEMY_DATABASE_URL=sqlite:////app/products_crud_api.db
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
