"""Configurados schemas.py atualizado models.py

Revision ID: 9100fcee60eb
Revises: 03e1539f0b33
Create Date: 2024-11-02 15:25:25.032110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9100fcee60eb'
down_revision: Union[str, None] = '03e1539f0b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
