"""Update Product model to include new fields

Revision ID: 97f6f9b9484d
Revises: 9100fcee60eb
Create Date: 2024-11-05 13:26:08.060789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f6f9b9484d'
down_revision: Union[str, None] = '9100fcee60eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
